#!/bin/bash

# Neovim
case $(uname) in
  'Darwin')
    sudo easy_install pip virtualenv
    pip install --upgrade setuptools pip
    ;;
  'Linux')
    sudo pip2 install --upgrade setuptools pip
    sudo pip3 install --upgrade setuptools pip
    ;;
esac

pip2 install --user neovim
pip3 install --user neovim

# Python packages
pip install --user proselint yamllint

# Ruby packages
gem install mdl

# Go deps
go get github.com/tools/godep
go get github.com/Unknwon/bra

# Install asdf
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.3.0
# asdf node
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
sh ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
LATEST_NODE_VERSION=`asdf list-all nodejs | tail -n 1 | tr -d '\n'`
asdf install nodejs $LATEST_NODE_VERSION
asdf global nodejs $LATEST_NODE_VERSION


# Install npm and packages
npm install -g npm@latest
npm update -g npm

# Neo/vim deps
npm install -g babel-cli jsonlint jshint eslint babel-eslint jsonlint jshint \
eslint-plugin-filenames eslint-plugin-flowtype eslint-plugin-lodash-fp \
eslint-plugin-standard babel-plugin-module-resolver eslint-plugin-promise \
eslint-config-standard-react eslint-config-standard eslint_d \
flow-bin caniuse-cmd neovim-client csscomb emoj typescript tslint \
diff-so-fancy tern tern-fetch yarn sass-lint alex flow-language-server \
javascript-typescript-langserver

# airbnb-eslint
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)

# other node deps
npm install -g http-server plugman cordova grunt-cli tldr

# Mac deps
case $(uname) in
  'Darwin')
    # cordova-ios
    npm install -g ios-deploy ios-sim

    # vagrant
    vagrant plugin install vagrant-bindfs
    vagrant plugin install vagrant-hostmanager

    # ansible
    sudo chmod 600 ~/.netrc

    # fonts
    mkdir -p "$HOME/.dotfiles/vendor/fonts/"
    mkdir -p "$HOME/Library/Fonts"

    wget https://github.com/i-tu/Hasklig/releases/download/v1.0-beta/Hasklig-1.0-Beta.zip \
      -O "$HOME/.dotfiles/vendor/fonts/hasklig.zip"
    wget https://github.com/ryanoasis/nerd-fonts/releases/download/v0.8.0/SourceCodePro.zip \
      -O "$HOME/.dotfiles/vendor/fonts/iconfont.zip"

    unzip "$HOME/.dotfiles/vendor/fonts/hasklig.zip" -d "$HOME/.dotfiles/vendor/fonts/"
    unzip "$HOME/.dotfiles/vendor/fonts/iconfont.zip" -d "$HOME/.dotfiles/vendor/fonts/"

    find "$HOME/.dotfiles/vendor/fonts/" \
      -type f -name "*.*tf" -exec cp "{}" "$HOME/Library/Fonts/" \;
    fc-cache -vf ~/.fonts
    ;;
esac
