#!/bin/bash

# Neovim
case $(uname) in
  'Darwin')
    sudo easy_install pip virtualenv virtualenvwrapper
    pip install --upgrade setuptools pip
    pip3 install --upgrade setuptools pip
    pip install --user neovim
    pip3 install --user neovim
    ;;
  'Linux')
    pip install --user virtualenv virtualenvwrapper
    sudo pip2 install --upgrade setuptools pip
    sudo pip3 install --upgrade setuptools pip
    pip2 install --user neovim
    pip3 install --user neovim
    ;;
esac

# Install node
nvm install node
nvm alias default node

# Install npm and packages
npm install -g npm@latest
npm update -g npm

npm install -g flow-bin caniuse-cmd typescript diff-so-fancy yarn \
  http-server plugman cordova grunt-cli tldr heroku-cli less

# Lua dependencies
# install luarocks

# Mac deps
case $(uname) in
  'Darwin')
    # cordova-ios
    npm install -g ios-deploy ios-sim

    # fonts
    mkdir -p "$HOME/.dotfiles/vendor/fonts/"
    mkdir -p "$HOME/Library/Fonts"

    wget https://github.com/i-tu/Hasklig/releases/download/v1.0-beta/Hasklig-1.0-Beta.zip \
      -O "$HOME/.dotfiles/vendor/fonts/hasklig.zip"
    wget https://github.com/ryanoasis/nerd-fonts/releases/download/v0.8.0/SourceCodePro.zip \
      -O "$HOME/.dotfiles/vendor/fonts/iconfont.zip"

    unzip "$HOME/.dotfiles/vendor/fonts/hasklig.zip" -d "$HOME/.dotfiles/vendor/fonts/"
    unzip "$HOME/.dotfiles/vendor/fonts/iconfont.zip" -d "$HOME/.dotfiles/vendor/fonts/"

    find "$HOME/.dotfiles/vendor/fonts/" \
      -type f -name "*.*tf" -exec cp "{}" "$HOME/Library/Fonts/" \;
    fc-cache -vf ~/.fonts
    ;;
esac
