#!/bin/bash

# Neovim
case $(uname) in
  'Darwin')
    sudo easy_install pip virtualenv virtualenvwrapper
    sudo pip install --upgrade setuptools pip
    sudo pip3 install --upgrade setuptools pip
    pip install --user neovim
    pip3 install --user neovim
    ;;
  'Linux')
    sudo pip2 install --upgrade setuptools pip
    sudo pip3 install --upgrade setuptools pip
    pip2 install --user neovim
    pip3 install --user neovim
    pip install --user virtualenv virtualenvwrapper
    ;;
esac

# Install node
# no nvm yet need to setup zsh first
#nvm install node
#nvm alias default node

# Install npm and packages
#npm install -g npm@latest
#npm update -g npm

#npm install -g caniuse-cmd diff-so-fancy yarn http-server

# Lua dependencies
case $(uname) in
  'Linux')
    yaourt -S lua luarocks
    ;;
esac
