#!/bin/bash

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
source $HOME/.bash_profile
brew update
brew upgrade --all
brew install caskroom/cask/brew-cask
brew tap caskroom/versions
brew update

# Install essential packages
brew cask install java xquartz
brew install git git-flow ag wget zsh tmux reattach-to-user-namespace \
node python ruby rbenv ruby-build python3 elixir \
lua --universal --with-completion luajit --with-52compat \
vim --override-system-vi --with-lua --with-luajit --with-tcl

# Install Neovim
brew tap neovim/neovim
brew reinstall --HEAD neovim

# Install FZF
brew install --HEAD fzf

# Extras and related dependencies
brew install watch dict tree ncdu nmap htop mediainfo atool \
highlight ranger jq ant httpie gradle gcc \
imagemagick --with-webp graphicsmagick --with-webp \
ffmpeg --with-faac --with-fdk-aac --with-openssl --with-tools --with-webp \
android-sdk aspell --with-lang-es --with-lang-en \
weechat --with-aspell --with-curl --with-lua --with-perl --with-python --with-ruby \
inkscape --with-poppler pandoc w3m heroku-toolbelt

# Install Aqua apps
brew cask install alfred java kaleidoscope karabiner seil sourcetree slate \
transmission flux appcleaner keepingyouawake imageoptim imagealpha charles \
paw iterm2-nightly licecap webkit-nightly virtualbox vagrant unicodechecker \
firefox firefoxdeveloperedition teleport vlc virtualbox-extension-pack \
macid bartender

# Configure QuickLook
brew cask install qlcolorcode qlstephen qlmarkdown quicklook-json \
qlprettypatch quicklook-csv betterzipql qlimagesize webpquicklook \
suspicious-package

defaults write com.apple.finder QLEnableTextSelection -bool true && killall Finder
