#!/bin/bash

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
source $HOME/.bash_profile

# Install dependencies
cd bootstrap && brew bundle

# Install shell plugins
zplug install

# Enable text selection in QuickLook
defaults write com.apple.finder QLEnableTextSelection -bool true && killall Finder

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1

# Set a shorter Delay until key repeat
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# Add a context menu item for showing the Web Inspector in web views
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

# Show the ~/Library folder
chflags nohidden ~/Library

# iTerm ^H fix
case $(uname) in
  'Darwin')
    FIX='s/kbs=^[hH]/kbs=\\177/';
    infocmp $TERM | sed $FIX > $HOME/.dotfiles/vendor/$TERM.ti
    infocmp screen-256color | sed $FIX > $HOME/.dotfiles/vendor/screen-256color.ti
    tic $HOME/.dotfiles/vendor/$TERM.ti
    tic $HOME/.dotfiles/vendor/screen-256color.ti
    ;;
esac
