#!/bin/bash

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install dependencies
cd bootstrap && brew bundle

# Install BasicTex
open /usr/local/Caskroom/basictex/*/mactex-basictex-*.pkg
sudo tlmgr update --self
sudo tlmgr install setspace hyperref tucv lipsum dirtytalk latexmk latexindent chktex

# Dependencies for latexindent
# https://github.com/Glavin001/atom-beautify/issues/1792#issuecomment-327071117
sudo perl -MCPAN -e 'install "File::HomeDir"'
sudo cpan YAML::Tiny
sudo cpan Unicode::GCString

# Enable text selection in QuickLook
defaults write com.apple.finder QLEnableTextSelection -bool true && killall Finder

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1

# Set a shorter Delay until key repeat
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# Add a context menu item for showing the Web Inspector in web views
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

# Show the ~/Library folder
chflags nohidden ~/Library

# iTerm ^H fix
