#!/bin/bash

ROOT="${HOME}/.dotfiles/bootstrap"

case $(uname) in
  'Linux')
    source $ROOT/dependencies
    source $ROOT/symlink
    ;;
  'Darwin')
    source $ROOT/macos
    source $ROOT/dependencies
    source $ROOT/symlink
    ;;
esac
