#!/bin/bash

# go to dotfiles directory
cd "$HOME/.dotfiles" || exit

case $(uname) in
  'Darwin')
    # setup zsh
    sudo chpass -s "$(which zsh)" $USER

    # configure htop
    HTOP_VERSION=$(brew info htop | awk 'NR==1{ print $3 }')
    sudo chown root:wheel "/usr/local/Cellar/htop/$HTOP_VERSION/bin/htop"
    sudo chmod u+s "/usr/local/Cellar/htop/$HTOP_VERSION/bin/htop"

    # enable X extension for Slate/xdotool
    defaults write org.x.X11 enable_test_extensions -boolean true
    ;;

  'Linux')
    # gps
    sudo useradd --no-create-home --shell /usr/bin/nologin --user-group gps
    sudo gpasswd -a $USER gps
    newgrp gps
    # backlight
    sudo gpasswd -a $USER video
    newgrp video
    ;;
esac

# update submodules
git submodule update --init --recursive

# install configs with stow
stow zsh
stow tmux
stow git
stow vim
stow neovim
stow ag
stow weechat
stow ranger
stow npm
stow marker
stow psql
stow mysql

case $(uname) in
  'Darwin')
    stow hammerspoon
    stow karabiner
    ;;
  'Linux')
    stow xorg
    stow i3
    stow polybar
    stow defaults
    stow greenclip
    stow fonts
    stow gpg
    stow compton
    stow dunst
    stow autokey

    sudo stow --target=/ rxvt

    # peripherals
    # sudo stow --target=/ garmin
    # sudo stow --target=/ vmware
    # sudo stow --target=/ oculus

    # laptop
    sudo stow --target=/ thinkpad
    sudo stow --target=/ monitor
    sudo stow --target=/ backlight

    sudo rm /etc/dnsmasq.conf
    sudo stow --target=/ dnsmasq

    sudo systemctl daemon-reload
    sudo udevadm control --reload
    sudo udevadm trigger
    ;;
esac

# Install marker
$HOME/.marker/install.py
