#!/bin/bash

# stow installs
cd "$HOME/.dotfiles" || exit

stow zsh
stow tmux
stow git
stow vim
stow neovim
stow ag
stow weechat
stow ranger
stow asdf

case $(uname) in
  'Darwin')
    stow hammerspoon
    stow karabiner
    ;;
  'Linux')
    stow xorg
    stow i3
    ;;
esac

# Paths
ROOT="$HOME/.dotfiles"
WEECHAT="$ROOT/weechat"

# Update submodules
git submodule update --init --recursive

# Setup zsh
case $(uname) in
  'Darwin')
    sudo chpass -s "$(which zsh)" $USER
    ;;
esac

# Symlink Tmux Plugin Manager
ln -s "$HOME/.dotfiles/vendor/tpm" "$HOME/.tmux/plugins/tpm"

# iTerm ^H fix
case $(uname) in
  'Darwin')
    FIX='s/kbs=^[hH]/kbs=\\177/';
    infocmp $TERM | sed $FIX > $ROOT/vendor/$TERM.ti
    infocmp screen-256color | sed $FIX > $ROOT/vendor/screen-256color.ti
    tic $ROOT/vendor/$TERM.ti
    tic $ROOT/vendor/screen-256color.ti
    ;;
esac

# Hide last-logged-in message on new terminals
touch $HOME/.hushlogin

# Install fonts
case $(uname) in
  'Darwin')
    mkdir -p $ROOT/vendor/fonts/
    mkdir -p $HOME/Library/Fonts

    wget https://github.com/i-tu/Hasklig/releases/download/v1.0-beta/Hasklig-1.0-Beta.zip \
      -O $ROOT/vendor/fonts/hasklig.zip
    wget https://github.com/ryanoasis/nerd-fonts/releases/download/v0.8.0/SourceCodePro.zip \
      -O $ROOT/vendor/fonts/iconfont.zip

    unzip $ROOT/vendor/fonts/hasklig.zip -d $ROOT/vendor/fonts/
    unzip $ROOT/vendor/fonts/iconfont.zip -d $ROOT/vendor/fonts/

    find $ROOT/vendor/fonts/ \
      -type f -name "*.*tf" -exec cp "{}" $HOME/Library/Fonts/ \;
    fc-cache -vf ~/.fonts
    ;;
esac

# Configure htop
case $(uname) in
  'Darwin')
      HTOP_VERSION=$(brew info htop | awk 'NR==1{ print $3 }')
      sudo chown root:wheel /usr/local/Cellar/htop/$HTOP_VERSION/bin/htop
      sudo chmod u+s /usr/local/Cellar/htop/$HTOP_VERSION/bin/htop
      ;;
esac

# Elixir
touch $HOME/.iex.exs
rm -rf $HOME/.iex.exs
ln -s $ROOT/iex/iex.exs $HOME/.iex.exs

# Enable X extension for Slate/xdotool
case $(uname) in
  'Darwin')
    defaults write org.x.X11 enable_test_extensions -boolean true
    ;;
esac

# Setup imgcat
chmod +x $ROOT/bin/imgcat

# Setup Go
case $(uname) in
  'Darwin')
    mkdir $HOME/Development/SDK/gopath
    ;;
esac

    ;;
esac
