#!/bin/bash

# Dotfiles path
ROOT="${HOME}/.dotfiles"

# Xorg
mkdir -p $HOME/.xinitrc.d
chmod a+x $ROOT/xorg/xinit.sh
ln -s $ROOT/xorg/Xresources $HOME/.Xresources
ln -s $ROOT/xorg/Xmodmap $HOME/.Xmodmap
ln -s $ROOT/xorg/xinitrc $HOME/.xinitrc

# Create Symlinks
ln -s $ROOT/zsh/zshrc $HOME/.zshrc
ln -s $ROOT/zsh/zshenv $HOME/.zshenv
ln -s $ROOT/tmux/tmux.conf $HOME/.tmux.conf
ln -s $ROOT/zathura/zathurarc $HOME/.config/zathura
ln -s $ROOT/cmus/autosave $HOME/.config/cmus/autosave
ln -s $ROOT/git/gitconfig $HOME/.gitconfig
ln -s $ROOT/git/gitignore_global $HOME/.gitignore_global
ln -s $ROOT/slate/slate $HOME/.slate
ln -s $ROOT/slate/slate.js $HOME/.slate.js
ln -s $ROOT/vim .$HOME/vim
ln -s $ROOT/vim/vimrc $HOME/.vimrc
ln -s $ROOT/vim/gvimrc $HOME/.gvimrc
ln -s $ROOT/vendor/vim-plug/plug.vim $ROOT/vim/autoload/plug.vim
ln -s $ROOT/ag/agignore .agignore
ln -s $ROOT/ack/ackrc $HOME/.ackrc
ln -s $ROOT/vendor/pure/pure.zsh \
      /usr/local/share/zsh/site-functions/prompt_pure_setup

# Hide last-logged-in message on new terminals
touch $HOME/.hushlogin

# Create go path
mkdir -p $HOME/Development/SDK/gopath

# Add urxvt fonts
mkdir $HOME/.fonts

unzip -o $ROOT/vendor/meslo/dist/v1.2.1/Meslo\ LG\ DZ\ v1.2.1.zip \
  -d /tmp
find /tmp/Meslo\ LG\ DZ\ v1.2.1 -type f -name "*.ttf" \
  -exec cp "{}" $HOME/.fonts/ \;
find $ROOT/vendor/powerline-fonts -type f -name "*.*tf" \
  -exec ln -s "{}" $HOME/.fonts \;
find $ROOT/vendor/powerline-fonts -type f -name "*.pcf.gz" \
  -exec ln -s "{}" $HOME/.fonts \;
fc-cache -vf ~/.fonts

# Interactive font size for urxvt
mkdir -p $HOME/.urxvt/ext/
chmod +x $ROOT/vendor/urxvt-font-size
ln -s $ROOT/vendor/urxvt-font-size/font-size $HOME/.urxvt/ext

# Tab extensions for urxvt
chmod +x $ROOT/vendor/urxvt-tabbedex/tabbedex
ln -s $ROOT/vendor/urxvt-tabbedex/tabbedex $HOME/.urxvt/ext

# Enable X extension for Slate/xdotool
defaults write org.macports.X11 enable_test_extensions -boolean true
defaults write org.x.X11 enable_test_extensions -boolean true

defaults write org.macports.X11 app_to_run urxvtc
defaults write org.x.X11 app_to_run urxvtc
