#!/bin/bash

# Paths
ROOT="${HOME}/.dotfiles"
WEECHAT="${ROOT}/weechat"

# Clone the repository
git clone --recursive git@github.com:disusered/dotfiles.git $HOME/.dotfiles

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
source $HOME/.bash_profile
brew update
brew upgrade --all
brew install caskroom/cask/brew-cask

# Install essential packages
brew cask install java xquartz
brew install git git-flow ag wget zsh tmux reattach-to-user-namespace \
node --without-npm python lua --universal --with-completion luajit --with-52compat \
vim --override-system-vi --with-lua --with-luajit --with-tcl

# Install Neovim
brew tap neovim/neovim
brew reinstall --HEAD neovim
pip install --upgrade setuptools
pip install --upgrade pip
pip install neovim

# Install FZF
brew install --HEAD fzf

# Symlink zsh configs and install
rm $HOME/.zshrc $HOME/.zshenv
ln -s $ROOT/zsh/zshrc $HOME/.zshrc
ln -s $ROOT/zsh/zshenv $HOME/.zshenv
sudo chpass -s /bin/zsh $USER

# Symlink Tmux config
rm $HOME/.tmux.conf
ln -s $ROOT/tmux/tmux.conf $HOME/.tmux.conf

# Symlink Git config
rm $HOME/.gitconfig $HOME/.gitignore_global
ln -s $ROOT/git/gitconfig $HOME/.gitconfig
ln -s $ROOT/git/gitignore_global $HOME/.gitignore_global

# Symlink Slate confi
rm $HOME/.slate $HOME/.slate.js
ln -s $ROOT/slate/slate.js $HOME/.slate.js

# Symlink Vim config and install plugins
rm $HOME/.vim $HOME/.vimrc $HOME/.gvimrc $ROOT/vim/autoload/plug.vim
mkdir -p $ROOT/vim/autoload
ln -s $ROOT/vim $HOME/.vim
ln -s $ROOT/vim/vimrc $HOME/.vimrc
ln -s $ROOT/vim/gvimrc $HOME/.gvimrc
ln -s $ROOT/vendor/vim-plug/plug.vim $ROOT/vim/autoload/plug.vim
vim +PlugInstall +qall

# Symlink Neovim config and install plugins
rm $HOME/.nvim $HOME/.nvimrc $ROOT/vim/autoload/plug.vim
mkdir -p $ROOT/vim/autoload
ln -s $ROOT/vim $HOME/.nvim
ln -s $ROOT/vim/nvimrc $HOME/.nvimrc
ln -s $ROOT/vendor/vim-plug/plug.vim $ROOT/vim/autoload/plug.vim
nvim +PlugInstall +qall

# iTerm ^H fix
FIX='s/kbs=^[hH]/kbs=\\177/';
infocmp $TERM | sed $FIX > $ROOT/vendor/$TERM.ti
infocmp screen-256color | sed $FIX > $ROOT/vendor/screen-256color.ti
tic $ROOT/vendor/$TERM.ti
tic $ROOT/vendor/screen-256color.ti

# Symlink Ag config
rm $HOME/.agignore
ln -s $ROOT/ag/agignore $HOME/.agignore

# Hide last-logged-in message on new terminals
touch $HOME/.hushlogin

# Install fonts
rm -rf $HOME/.fonts
mkdir -p $HOME/Library/Fonts $HOME/.fonts
unzip -o $ROOT/vendor/meslo/dist/v1.2.1/Meslo\ LG\ DZ\ v1.2.1.zip \
  -d /tmp
find /tmp/Meslo\ LG\ DZ\ v1.2.1 -type f -name "*.ttf" \
  -exec cp "{}" $HOME/.fonts/ \;
find $ROOT/vendor/powerline-fonts -type f -name "*.*tf" \
  -exec cp "{}" $HOME/.fonts/ \;
find $ROOT/vendor/powerline-fonts -type f -name "*.pcf.gz" \
  -exec cp "{}" $HOME/.fonts/ \;
find $HOME/.fonts -type f -name "*.*tf" \
  -exec cp "{}" $HOME/Library/Fonts/ \;
fc-cache -vf ~/.fonts

# Install npm and packages
curl -L https://npmjs.com/install.sh | sh
npm update npm -g
npm adduser
npm install -g yo gulp grunt-cli cordova ionic http-server forever \
ios-deploy ios-sim jshint karma-cli bower nesh caniuse-cmd \
node-inspector nodemon phonegap plugman svgo wiredep browserify \
david eslint babel-eslint flow-bin csscomb babel eslint-plugin-react \
mocha jsonlint neovim-client
nesh --enable nesh-lodash
nesh --enable nesh-history-search

# Python Packages
pip install requests websocket-client pync pafy rainbowstream

# Ruby
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
\curl -sSL https://get.rvm.io | bash -s stable
rvm install ruby-2.1.2 ruby-2.2.0 && rvm use 2.2.0

# PHP
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

# Extras and related dependencies
brew install watch dict tree ncdu nmap htop mediainfo atool \
highlight ranger watchman flow jq ansible ant httpie gradle gcc \
imagemagick --with-webp graphicsmagick --with-webp \
ffmpeg --with-faac --with-fdk-aac --with-openssl --with-tools --with-webp \
planck homebrew/x11/xdotool aspell --with-lang-es --with-lang-en \
weechat --with-aspell --with-curl --with-lua --with-perl --with-python --with-ruby

# Configure htop
HTOP_VERSION=$(brew info htop | awk 'NR==1{ print $3 }')
sudo chown root:wheel /usr/local/Cellar/htop-osx/$HTOP_VERSION/bin/htop
sudo chmod u+s /usr/local/Cellar/htop-osx/$HTOP_VERSION/bin/htop

# Rainbow
ln -s $ROOT/rainbow/rainbow_config.json .rainbow_config.json

# Weechat
rm -rf $HOME/.weechat
ln -s $WEECHAT $HOME/.weechat

# Add Interactive font resizing for urxvt
mkdir -p $HOME/.urxvt/ext/
chmod +x $ROOT/vendor/urxvt-font-size
rm $HOME/.urxvt/ext/font-size
ln -s $ROOT/vendor/urxvt-font-size/font-size $HOME/.urxvt/ext/font-size

# Install tab extensions for urxvt
chmod +x $ROOT/vendor/urxvt-tabbedex/tabbedex
rm $HOME/.urxvt/ext/tabbedex
ln -s $ROOT/vendor/urxvt-tabbedex/tabbedex $HOME/.urxvt/ext/tabbedex

# Enable X extension for Slate/xdotool
defaults write org.x.X11 enable_test_extensions -boolean true
defaults write org.x.X11 app_to_run urxvtc

# Xorg
mkdir -p $HOME/.xinitrc.d
rm $HOME/.Xresources $HOME/.Xmodmap $HOME/.xinitrc
ln -s $ROOT/xorg/Xresources $HOME/.Xresources
ln -s $ROOT/xorg/Xmodmap $HOME/.Xmodmap
ln -s $ROOT/xorg/xinitrc $HOME/.xinitrc
