" NeoBundle =======================================================================
  set nocompatible
  filetype off

  set runtimepath+=~/.dotfiles/vendor/neobundle.vim/
  call neobundle#begin(expand('~/.dotfiles/vendor/bundles.vim/'))

  let g:neobundle#install_process_timeout = 600

  " yo dawg
  NeoBundleFetch 'Shougo/neobundle.vim'
  " bundles
    " base16 colorschemes
    NeoBundle 'chriskempson/base16-vim'
    " easymotion
    NeoBundle 'Lokaltog/vim-easymotion'
    " supertab
    NeoBundle 'ervandew/supertab'
    " dispatch
    NeoBundle 'tpope/vim-dispatch'
    " syntastic
    NeoBundle 'scrooloose/syntastic'
    " nerdtree
    NeoBundle 'scrooloose/nerdtree'
    " surround
    NeoBundle 'tpope/vim-surround'
    " speeddating
    NeoBundle 'tpope/vim-speeddating'
    " abolish
    NeoBundle 'tpope/vim-abolish'
    " easy-align
    NeoBundle 'junegunn/vim-easy-align'
    " commentary
    NeoBundle 'tpope/vim-commentary'
    " unimpaired
    NeoBundle 'tpope/vim-unimpaired'
    " airline
    NeoBundle 'bling/vim-airline'
    " repeat
    NeoBundle 'tpope/vim-repeat'
    " fugitive
    NeoBundle 'tpope/vim-fugitive'
    " gitv
    NeoBundle 'gregsexton/gitv'
    " gitgutter
    NeoBundle 'airblade/vim-gitgutter'
    " editorconfig
    NeoBundle 'editorconfig/editorconfig-vim'
    " tagbar
    NeoBundle 'majutsushi/tagbar'
    " tmuxline
    " NeoBundle 'edkolev/tmuxline.vim'
    " delimitor
    NeoBundle 'Raimondi/delimitMate'
    " local vimrc
    NeoBundle 'MarcWeber/vim-addon-local-vimrc'
    " json
    NeoBundle 'elzr/vim-json'
    " handlebars
    NeoBundle 'mustache/vim-mustache-handlebars'
    " tmux nav
    NeoBundle 'christoomey/vim-tmux-navigator'
    " vim slime
    NeoBundle 'jpalardy/vim-slime'
    " ultisnips
    NeoBundle 'SirVer/ultisnips'
    " togglecursor
    NeoBundle 'jszakmeister/vim-togglecursor'
    " ctrlp
    NeoBundle 'kien/ctrlp.vim'
    NeoBundle 'FelikZ/ctrlp-py-matcher'
    NeoBundle 'tacahiroy/ctrlp-funky'
    " narrow region
    NeoBundle 'chrisbra/NrrwRgn'
    " goyo
    NeoBundle 'junegunn/goyo.vim'
    " markdown
    NeoBundle 'gabrielelana/vim-markdown'
    " dash
    NeoBundle 'rizzatti/dash.vim'
    " docker
    NeoBundle 'honza/dockerfile.vim'
    " notes
    NeoBundle 'xolox/vim-notes', {
                \ 'depends': [
                \     'xolox/vim-misc',
                \ ]
                \}
    " autocomplete
    NeoBundle 'Valloric/YouCompleteMe', {
                \ 'build': {
                \   'unix': './install.sh',
                \   'mac': './install.sh'
                \ }
                \}

    " ruby
    NeoBundleLazy 'vim-ruby/vim-ruby', {
                \ 'depends': [
                \ ],
                \ 'autoload': {
                \   'filetypes': ['ruby', 'eruby']
                \ },
                \}

    NeoBundleLazy 'tpope/vim-rails', {
                \ 'depends': [
                \ ],
                \ 'autoload': {
                \   'filetypes': ['ruby', 'eruby']
                \ },
                \}


    NeoBundleLazy 'tpope/vim-endwise', {
                \ 'depends': [
                \ ],
                \ 'autoload': {
                \   'filetypes': ['ruby', 'eruby']
                \ },
                \}

    NeoBundleLazy 'tpope/vim-bundler', {
                \ 'depends': [
                \     'tpope/vim-projectionist',
                \ ],
                \ 'autoload': {
                \   'filetypes': ['ruby', 'eruby']
                \ },
                \}

    " coffeescript
    au BufNewFile,BufRead {*.coffee,*.litcoffee} set filetype=coffee
    NeoBundleLazy 'kchmck/vim-coffee-script', {
                \ 'autoload': {
                \   'filetypes': ['coffee']
                \ },
                \}


    " javascript
    NeoBundle 'moll/vim-node'
    NeoBundleLazy 'othree/yajs.vim', {
                \ 'autoload': {
                \   'filetypes': ['javascript']
                \ },
                \}

    NeoBundleLazy 'othree/javascript-libraries-syntax.vim', {
                \ 'autoload': {
                \   'filetypes': ['javascript', 'coffee', 'typescript']
                \ },
                \}

    NeoBundleLazy 'heavenshell/vim-jsdoc', {
                \ 'autoload': {
                \   'filetypes': ['javascript']
                \ },
                \}

    NeoBundleLazy 'marijnh/tern_for_vim', {
                \ 'autoload': {
                \   'filetypes': ['javascript']
                \ },
                \ 'build' : {
                \    'unix' : 'npm install',
                \    'mac' : 'npm install'
                \ },
                \}

    " emmet
    NeoBundleLazy 'mattn/emmet-vim', {
                \ 'autoload': {
                \   'filetypes': ['javascript', 'html', 'css', 'eruby']
                \ },
                \}

    NeoBundleLazy 'csscomb/vim-csscomb', {
                \ 'autoload': {
                \   'filetypes': ['css', 'scss']
                \ },
                \}

    " markdown
    NeoBundleLazy 'itspriddle/vim-marked', {
                \ 'autoload': {
                \   'filetypes': ['markdown', 'ghmarkdown']
                \ },
                \ }

  call neobundle#end()
  filetype plugin indent on
  NeoBundleCheck

" etc ==========================================================================
  " set encoding
  set encoding=utf-8

  " remap leader key
  let mapleader = ","

  " enable mouse
  set mouse=a
  set ttymouse=xterm2

  " disable ex
  nnoremap Q <nop>

  " close
  nnoremap <leader>q :bp\|bd #<CR>

  " use unix as the standard file type
  set ffs=unix,dos,mac

  " enable system clipboard
  set clipboard=unnamed

  " enable filetype plugins
  filetype plugin on
  filetype indent on

  " set to auto read when a file is changed from the outside
  set autoread

  " enable bg buffers
  set hidden

  " text editor
  set ruler
  set number
  set title
  set backspace=indent,eol,start
  set nostartofline
  set nowrap
  set colorcolumn=80
  set nofoldenable

  " whitespace
  set tabstop=2
  set shiftwidth=2
  set softtabstop=2
  set expandtab
  set autoindent
  set copyindent
  set pastetoggle=<F2>

  " whitespace characters
  " set listchars=trail:␣,tab:⇥ᐧ,nbsp:⍽,eol:¶,extends:▸,precedes:◂
  set list
  set listchars=trail:·,tab:⇥ᐧ

  " remove trailing whitespace
  nnoremap <silent> <Leader>rt :%s/\s\+$//e<CR>

  " switch off current search
  nnoremap <silent> <Leader>h :nohlsearch<CR>

  " bubble single lines
  nmap ˚ [e
  nmap ∆ ]e

  " bubble multiple lines
  vmap ˚ [egv
  vmap ∆ ]egv

  " close window
  map <silent> <F4> :bw<CR>

  " file explorer
  let g:netrw_liststyle = 3

  " colors
  syntax enable

  " base16-shell 256 color
  let base16colorspace=256
  colorscheme base16-tomorrow

  set background=dark

  " fully collapse vertical splits
  set wmh=0

  " search
  set hlsearch
  set incsearch
  set ignorecase
  set smartcase

  " ignore compiled files
  set wildignore=*.o,*~,*.pyc
  if has("win16") || has("win32")
      set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
  else
      set wildignore+=.git\*,.hg\*,.svn\*
  endif

  " turn backup off
  set nobackup
  set nowb
  set noswapfile

" syntax specific ==============================================================
  " make
  au FileType make set noexpandtab

  " markdown
  autocmd BufNewFile,BufReadPost *.md set filetype=markdown

  " additional ruby extensions
  au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru,compass.config} set ft=ruby

  " additional js extensions
  au BufNewFile,BufRead {*.json,.jshintrc,.tern-project} set ft=json

  " additional handlebars extensions
  au BufNewFile,BufRead {*.hbs,*.handlebars} set ft=mustache

" plugin specific ==============================================================
  " easymotion
  let g:EasyMotion_smartcase = 1
  nmap <Space> <Plug>(easymotion-bd-t2)
  map  / <Plug>(easymotion-sn)
  omap / <Plug>(easymotion-tn)

  " commentary
  nmap <Leader>/ gcc
  vmap <Leader>/ gc

  " syntastic
  function s:find_jshintrc(dir)
    let l:found = globpath(a:dir, '.jshintrc')
    if filereadable(l:found)
        return l:found
    endif

    let l:parent = fnamemodify(a:dir, ':h')
    if l:parent != a:dir
        return s:find_jshintrc(l:parent)
    endif

    return "~/.dotfiles/vim/jshintrc"
  endfunction
  function UpdateJsHintConf()
    let l:dir = expand('%:p:h')
    let l:jshintrc = s:find_jshintrc(l:dir)
    let g:syntastic_javascript_jshint_conf = l:jshintrc
    let g:syntastic_javascript_jshint_args = '--config ' + l:jshintrc
  endfunction
  map <silent> <Leader>l :w<CR>:SyntasticCheck<CR>:Errors<CR>
  let g:syntastic_html_checkers=['']

  " airline
  set laststatus=2
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#show_buffers = 1
  let g:airline#extensions#tabline#buffer_nr_show = 1

  " marked
  nnoremap <silent> <Leader>md :MarkedOpen!<CR>

  " local vimrc
  let g:local_vimrc = {'names':['.local-vimrc'],'hash_fun':'LVRHashOfFile'}

  " delimit
  let g:delimitMate_expand_cr = 1

  " json
  let g:vim_json_syntax_conceal = 0

  " tern
  let g:tern_show_argument_hints='no'
  let g:tern_show_signature_in_pum = 1

  " fugitive
  nnoremap <Leader>gs :Gstatus<CR>
  nnoremap <Leader>ga :Gcommit --amend<CR>
  nnoremap <Leader>gc :Gcommit -v -q<CR>
  nnoremap <Leader>gt :Gcommit -v -q %:p<CR>
  nnoremap <Leader>gd :Gdiff<CR>
  nnoremap <Leader>gr :Gread<CR>
  nnoremap <Leader>ge :Gedit<CR>
  nnoremap <Leader>gw :Gwrite<CR><CR>
  nnoremap <Leader>gl :Gitv<CR>
  nnoremap <Leader>gh :Gitv!<CR>
  nnoremap <Leader>gp :Ggrep<Space>
  nnoremap <Leader>gm :Gmove<Space>
  nnoremap <Leader>gb :Git branch<Space>
  nnoremap <Leader>go :Git checkout<Space>
  nnoremap <Leader>gps :Dispatch! git push<CR>
  nnoremap <Leader>gpl :Dispatch! git pull<CR>

  " youcompleteme
  let g:ycm_autoclose_preview_window_after_completion = 1
  let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
  let g:ycm_enable_diagnostic_signs = 0

  " jsdoc
  let g:jsdoc_default_mapping = 0
  let g:jsdoc_allow_input_prompt = 1
  nnoremap <silent> <Leader>jsd :JsDoc<CR>

  " easy-align
  vmap <Enter> <Plug>(LiveEasyAlign)

  " slime
  let g:slime_target = "tmux"
  let g:slime_paste_file = tempname()
  let g:slime_default_config = {"socket_name": "default", "target_pane": "1"}

  " ultisnips
  " make ycm compatible with ultisnips (using supertab)
  let g:ycm_key_list_select_completion = ['<c-n>', '<down>']
  let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
  let g:SuperTabDefaultCompletionType = '<C-n>'
  " better key bindings for ultisnipsexpandtrigger
  let g:UltiSnipsExpandTrigger = "<tab>"
  let g:UltiSnipsJumpForwardTrigger = "<tab>"
  let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"

  " ctrlp
  let g:ctrlp_match_func = { 'match': 'pymatcher#PyMatch' }
  let g:ctrlp_clear_cache_on_exit = 0
  let g:ctrlp_max_files = 0
  let g:ctrlp_user_command = 'ag %s -i --nocolor --nogroup --hidden -g ""'
  let g:ctrlp_extensions = ['funky']

  " bindings
  nnoremap <leader>p :CtrlP<CR>
  nnoremap <leader>t :CtrlPBuffer<CR>
  nnoremap <leader>o :CtrlPFunky<CR>

  " tagbar
  let g:tagbar_left = 0
  let g:tagbar_sort = 0
  nmap + :TagbarToggle<CR>

  " nerdtree
  map = :NERDTreeToggle<CR>
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

  " goyo
  nnoremap <silent> <Leader>dfm :Goyo<CR>
  function! GoyoBefore()
    set wrap
  endfunction
  function! GoyoAfter()
    set nowrap
  endfunction
  let g:goyo_callbacks = [function('GoyoBefore'), function('GoyoAfter')]

  " ruby
  let g:rubycomplete_buffer_loading = 1
  let g:rubycomplete_classes_in_global = 1
  let g:rubycomplete_rails = 1
  let g:rubycomplete_use_bundler = 1

  " dash
  nmap <silent> <leader>d <Plug>DashSearch

  " tmux
  " let g:airline#extensions#tmuxline#enabled = 0
  " let g:tmuxline_theme = 'vim_statusline_1'

  " eclim
  let g:airline#extensions#eclim#enabled = 1
  let g:EclimCompletionMethod = 'omnifunc'
  let g:EclimJavascriptLintConf = '~/.dotfiles/vim/jslrc'
  let g:EclimJavascriptValidate = 0
  nmap <F6> :ProjectsTree<CR>

  " notes
  let g:notes_directories = ['~/Dropbox/Notes']
  let g:notes_tagsindex = '~/.dotfiles/vim/note_tags'

  " check for updates
  NeoBundleCheck
