require("config.treesitter")
require("config.filebeagle")
require("config.telescope")
require("config.colorizer")
require("config.tokyonight")
require("config.lualine")
require("config.gitsigns")
require("config.fugitive")
