" Init =========================================================================
  let $MYCONFIG="$HOME/.dotfiles/nvim/config"

  set nocompatible
  filetype off

  call plug#begin('~/.dotfiles/vendor/nplugged')

  " Visual
  Plug 'chriskempson/base16-vim'
  Plug 'itchyny/lightline.vim'

  " Source Control
  Plug 'tpope/vim-fugitive'
  Plug 'airblade/vim-gitgutter'

  " Editor
  Plug 'benekastah/neomake'
  Plug 'Valloric/YouCompleteMe', { 'do': './install.sh' }

  " Javascript
  au BufNewFile,BufRead {*.es6} set ft=javascript
  Plug 'heavenshell/vim-jsdoc',   { 'for': 'javascript' }
  Plug 'marijnh/tern_for_vim',    { 'for': 'javascript', 'do': 'npm install' }
  Plug 'pangloss/vim-javascript', { 'for': 'javascript' }

  " JSX
  au BufNewFile,BufRead {*.jsx} set ft=jsx
  Plug 'mxw/vim-jsx', { 'for': 'jsx' }

  " JSON
  au BufNewFile,BufRead {*.json,*jshintrc,*tern-project,*jscsrc} set ft=json

" Conditional ===================================================================
  au BufRead,BufNewFile {*.md,*.markdown} set filetype=markdown
  au BufNewFile,BufRead {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru,compass.config} set ft=ruby
  au BufNewFile,BufRead {*gitconfig} set ft=gitconfig
  au BufNewFile,BufRead {*.hbs,*.handlebars} set ft=mustache
  au BufNewFile,BufRead {*Dockerfile} set filetype=dockerfile
  au BufNewFile,BufRead {*.coffee,*.litcoffee} set filetype=coffee
  au BufNewFile,BufRead {*.jade} set filetype=jade
  au BufNewFile,BufRead {*zshrc,*zshenv} set filetype=zsh.sh
  au BufNewFile,BufRead {.env} set filetype=sh

  call plug#end()
  filetype plugin indent on

" Autocommands
  au FileType make set noexpandtab
  au FileType gitconfig set noexpandtab
  au FileType css setlocal omnifunc=csscomplete#CompleteCSS
  au FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
  au FileType python setlocal omnifunc=pythoncomplete#Complete
  au FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
  au FileType gitcommit setlocal omnifunc=pickler#omnifunc
  au FileType javascript setlocal omnifunc=tern#Complete

  au BufWritePost *.py,*.js Neomake

" Settings =====================================================================
source $MYCONFIG/vim.vim
source $MYCONFIG/neomake.vim
source $MYCONFIG/lightline.vim
source $MYCONFIG/youcompleteme.vim
source $MYCONFIG/tern.vim
