" let g:UltiSnipsExpandTrigger = '<tab>'
" let g:UltiSnipsJumpForwardTrigger = '<tab>'
" let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
let g:coc_snippet_next = '<c-j>'
let g:coc_snippet_prev = '<c-k>'
