#!/bin/sh
#
# ~/.xinitrc

# Load settings
xrdb $HOME/.Xresources

# Note that startup items are run in the background with the & suffix added.
# Otherwise the script would halt and wait for each program and daemon to exit
# before executing the window manager, which isn't backgrounded.

# Startup
exec urxvtd \
  --fork \
  --opendisplay \
  --quiet &

# Window manager
exec quartz-wm

# Enable pasteboard integration with quartz-wm proxy
# /usr/bin/quartz-wm --only-proxy & exec /opt/local/bin/wmake
