let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_start_length = 1
let g:deoplete#max_menu_width = 80
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['buffer']
let g:deoplete#sources = {}
let g:deoplete#sources.javascript = ['omni']
let g:deoplete#sources.jsx = ['omni']
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.javascript = '[^. \t]\.\w*'
let g:deoplete#omni_patterns.jsx = '[^. \t]\.\w*'
