# Set function paths
fpath=(
  /usr/local/share/zsh/site-functions
  $fpath
)

# Vi mode
bindkey -v

# Autoload modules
autoload -U compinit && compinit
autoload -U promptinit && promptinit

# Set prompt
prompt pure

# History
SAVEHIST=10000
HISTSIZE=10000
HISTFILE=$HOME/.zsh_history

setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY
setopt HIST_BEEP

# Environment variables
export LANG='en_US.UTF-8'

export BROWSER='open'
export EDITOR='vim'
export PAGER='less'
export LESS='-X -F -g -i -M -R -S -w -z-4'

export ANDROID_HOME='/usr/local/opt/android-sdk'
export JAVA_HOME=`/usr/libexec/java_home`
export VAGRANT_DEFAULT_PROVIDER=virtualbox
export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/carlos/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

# Aliases
alias c='clear'
alias ls='ls -G'
alias ag='ag --pager "less -R" --color-line-number 1\;35 --color-path 1\;37 --color-match 7\;34'
alias http='http --style vim'

alias g='git'
alias gl='g l'
alias gs='g s'
alias gb='g b'
alias gbc='g bc'
alias gc='g c'
alias gca='g ca'
alias gcm='g cm'
alias gg='g g'
alias ga='g a'
alias gp='g p'
alias gpf='g pf'
alias gd='g d'
alias gdt='g dt'
alias gm='g m'
alias gmt='g mt'
alias gf='g f'
alias gfm='g fm'
alias gco='g co'
alias gst='g st'
alias gsl='g sl'
alias gss='g ss'
alias gsa='g sa'

# Temporary files
export TMPDIR="/tmp/$USER"
if [[ ! -d "$TMPDIR" ]]; then
  mkdir -p -m 700 "$TMPDIR"
fi
TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

# fn Keys
bindkey "^[[H" beginning-of-line    # fn ←
bindkey "^[[F" end-of-line          # fn →
bindkey "^[[3~" delete-char         # fn delete

# Marks
export MARKPATH=$HOME/.marks
function jump {
  cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
}
function mark {
  mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"
}
function unmark {
  rm -i "$MARKPATH/$1"
}
function marks {
  \ls -l "$MARKPATH" | tail -n +2 | sed 's/  / /g' | cut -d' ' -f9- | awk -F ' -> ' '{printf "%-10s -> %s\n", $1, $2}'
}
function _completemarks {
  reply=($(ls $MARKPATH))
}
compctl -K _completemarks jump
compctl -K _completemarks unmark

# History substring search
if [ -f /usr/local/opt/zsh-history-substring-search/zsh-history-substring-search.zsh ]; then
  source /usr/local/opt/zsh-history-substring-search/zsh-history-substring-search.zsh
  zmodload zsh/terminfo
  # Bind arrows
  bindkey '^[[A' history-substring-search-up
  bindkey '^[[B' history-substring-search-down
  bindkey -M vicmd 'k' history-substring-search-up
  bindkey -M vicmd 'j' history-substring-search-down
fi

# Base16
BASE16_SCHEME="tomorrow"
if [ -f $HOME/.dotfiles/vendor/base16-shell/base16-$BASE16_SCHEME.dark.sh ]; then
  BASE16_SHELL="$HOME/.dotfiles/vendor/base16-shell/base16-$BASE16_SCHEME.dark.sh"
  [[ -s $BASE16_SHELL ]] && . $BASE16_SHELL
fi

# RVM
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
