# TODO: iterm - Home fn ←
# TODO: iterm - END fn → 
# TODO: urxvt - Home fn ←
# TODO: urxvt - END fn → 
source "${HOME}/.dotfiles/vendor/zgen/zgen.zsh"

# Check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

    # plugins
    zgen load zsh-users/zsh-syntax-highlighting
    zgen load zsh-users/zsh-history-substring-search
    zgen load mollifier/cd-gitroot

    # completions
    zgen completions zsh-users/zsh-completions src

    # theme
    zgen load sindresorhus/pure

    # save all to init script
    zgen save
fi

# Set path
path=(
  $HOME/Development/SDK/android-sdk/tools
  $HOME/Development/SDK/android-sdk/platform-tools
  $HOME/.macports/bin
  $HOME/.macports/sbin
  $path
)

# Set function paths
fpath=(
  /usr/local/share/zsh/site-functions
  $fpath
)

# Autoload modules
# autoload -U compinit && compinit

# History
SAVEHIST=10000
HISTSIZE=10000
HISTFILE=$HOME/.zsh_history

setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY
setopt HIST_BEEP

# Disable Globbing
alias git='noglob git'

# Aliases
alias c='clear'
alias e='ranger'
alias m='cmus'
alias d='dict'
alias cdg='cd-gitroot'
alias top='htop'
alias pdf='zathura'
alias pbc='pbcopy'
alias pbp='pbpaste'
alias web='$HOME/.macports/Library/Frameworks/Python.framework/Versions/3.4/bin/qutebrowser'
alias ztime='/usr/bin/time zsh -i -c exit'
alias ex='txt2regex'
alias use='ncdu'
alias p='feh --auto-zoom --scale-down --keep-zoom-vp'
alias tb='feh --auto-zoom --scale-down --keep-zoom-vp --thumbnails'
alias v='mplayer'
alias xt='urxvt'
alias ls='ls -G'
alias ag='ag --pager "less -R" --color-line-number 1\;35 --color-path 1\;37 --color-match 7\;34'
alias http='http --style vim'
alias n='cd $HOME/Dropbox/Notes && vim .'
alias fonts='fc-list | cut -f2 -d: | sort -u'
alias g='git'
alias gl='g l'
alias gs='g status --short --branch'
alias gb='g branch'
alias gbc='g checkout -b'
alias gc='g commit --verbose'
alias gca='g commit --verbose --amend'
alias gcm='g commit --message'
alias gg='g ack'
alias ga='g add'
alias gp='g push'
alias gpf='g push --force'
alias gd='g diff --no-ext-diff'
alias gdt='g difftool'
alias gm='g merge'
alias gmt='g mergetool'
alias gf='g fetch'
alias gfm='g pull'
alias gr='g reset'
alias grl='g reflog'
alias gco='g checkout'
alias ll='ls -l'
alias la='ls -la'

# Temporary files
if [[ ! -d "$TMPDIR" ]]; then
  mkdir -p -m 700 "$TMPDIR"
fi
TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

# Marks
function jump {
  cd -P "$MARKPATH/$1" 2>/dev/null || echo "No such mark: $1"
}
function mark {
  mkdir -p "$MARKPATH"; ln -s "$(pwd)" "$MARKPATH/$1"
}
function unmark {
  rm -i "$MARKPATH/$1"
}
function marks {
  \ls -l "$MARKPATH" | tail -n +2 | sed 's/  / /g' | cut -d' ' -f9- | awk -F ' -> ' '{printf "%-10s -> %s\n", $1, $2}'
}
function _completemarks {
  reply=($(ls $MARKPATH))
}
compctl -K _completemarks jump
compctl -K _completemarks unmark



ZSHELL=`which zsh`
zle-keymap-select () {
	if [[ $COLORTERM == "rxvt-xpm" ]] then
		if [ $KEYMAP = vicmd ]; then
				echo -ne "\033]12;#B294BB\007"
		else
				echo -ne "\033]12;#969896\007"
		fi
	fi
}
zle -N zle-keymap-select
zle-line-init () {
    zle -K viins
		if [[ $COLORTERM == "rxvt-xpm" ]] then
        echo -ne "\033]12;#969896\007"
    fi
}
zle -N zle-line-init

# Base16
BASE16_SCHEME="tomorrow"
if [ -f $HOME/.dotfiles/vendor/base16-shell/base16-$BASE16_SCHEME.dark.sh ]; then
  BASE16_SHELL="$HOME/.dotfiles/vendor/base16-shell/base16-$BASE16_SCHEME.dark.sh"
  [[ -s $BASE16_SHELL ]] && . $BASE16_SHELL
fi

man() {
  env LESS_TERMCAP_mb=$'\E[01;31m' \
  LESS_TERMCAP_md=$'\E[01;35;5;74m' \
  LESS_TERMCAP_me=$'\E[0m' \
  LESS_TERMCAP_se=$'\E[0m' \
  LESS_TERMCAP_so=$'\E[38;5;246m' \
  LESS_TERMCAP_ue=$'\E[0m' \
  LESS_TERMCAP_us=$'\E[04;38;5;146m' \
  man "$@"
}

# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

bindkey -v

# History substring search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# key bindings
bindkey "e[1~" beginning-of-line
bindkey "e[4~" end-of-line
bindkey "e[5~" beginning-of-history
bindkey "e[6~" end-of-history
bindkey "e[3~" delete-char
bindkey "e[2~" quoted-insert
bindkey "e[5C" forward-word
bindkey "eOc" emacs-forward-word
bindkey "e[5D" backward-word
bindkey "eOd" emacs-backward-word
bindkey "ee[C" forward-word
bindkey "ee[D" backward-word
bindkey "^H" backward-delete-word
# for rxvt
bindkey "e[8~" end-of-line
bindkey "e[7~" beginning-of-line
# for non RH/Debian xterm, can't hurt for RH/DEbian xterm
bindkey "eOH" beginning-of-line
bindkey "eOF" end-of-line
# for freebsd console
bindkey "e[H" beginning-of-line
bindkey "e[F" end-of-line
# completion in the middle of a line
bindkey '^i' expand-or-complete-prefix
